:page-title: Experiences with setting up Gatsby
:page-category: Gatsby
:page-publishdate: 2020-12-13

= Experiences with setting up Gatsby

I wanted to setup a blog for myself and confronted myself with the problem of finding a platform to build my blog on.

First I wanted to do it the manual way and implement everything myself, but why go through all the hassle, when there are already so much Implementations out there?
I didn't wanted to reinvent the wheel, and also keep it lightweight and easily deployable.
So I stumbled across https://gohugo.io[Hugo] which sounded interesting and still is, especially because I want to learn GoLang anyway. After a small chat with my colleague https://www.larskoelpin.de[Lars] in which I explained my idea, Lars recommended me to use https://www.gatsbyjs.com[GatsbyJS].

Ok - so off we go and try out GatsbyJS.

== Installation

The initial installation and setup of Gatsby was pretty easy.
The process is described thoroughly in tutorials and documentations on their website.

Therefore, anyone that wants to try out setting up a gatsby website, shouldn't encounter too big issues while following
the official gatsby https://www.gatsbyjs.com/tutorial/[tutorials]. Even if you're new to setting up websites. Though basic knowledge of HTML, CSS, and JavaScript is obviously required. Knowledge in https://reactjs.org[ReactJS] definetely helps. If you're not familiar with ReactJS, it can be a good idea to check that out first.

Since I already knew TypeScript it was a no-brainer to me to transpose all the javascript files to typescript files.
Keep in mind, that it is not supported to change the gatsby configuration files to typescript files.

Although I have linked the Tutorials I want to give a quick overview of the commands I executed.

[source, shellsession]
.To install Gatsby
----
% sudo npm i -g gatsby-cli
----

To make some first steps with my new Project I used the hello-world starter by GatsbyJS.

[source, shellsession]
.Create a new Project
----
blog % gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world
----

[source, shellsession]
.Run the Gatsby Develop Environment
----
blog % gatsby develop
----

=== AsciiDoctor Transformer

Since I wanted to use asciidoctor files as blog entry I also installed the gatsby-transformer-asciidoc plugin. More on that later.
[source, shellsession]
----
% npm install gatsby-transformer-asciidoc
----

=== Styled Components

I wanted to work with styled components so I installed that as well

[source, shellsession]
.Install Styled-Components
----
% npm install gatsby-plugin-styled-components styled-components babel-plugin-styled-components
% npm i --save-dev @types/styled-components <1>
----
<1> Since I'm using typescript I also had to install the Typescript Types

== Experiences with Gatsby itself

To be honest, after setting up all the Gatsby Magic with your chosen fancy plugins and config files - other than running gatsby develop - you won't very much notice that you're using Gatsby. At least while developing.

=== Gatsby Config
The setup of the Gatsby Config is also very well documented in the tutorials, that's why I am skipping a detailed guide for this blog entry.
Additionally, the config is also self-explanatory for the simpler fields and including plugins is pretty straight forward too. 

What's way more noticeable is GraphQL. If you have never worked with GraphQL you will quickly start liking it. With GraphQL you can basically query data for further usage in your React Components. It's fast, very easy to use and very mighty.

=== Gatsby Nodes
I'm using it to query my Asciidoctor files in my blog directory and I can also query page-attributes that I define in my asciidoctor files.
When you're using the asciidocter-transformer you will need to implement a gatsby-node.js file in which you create nodes so that the data is available via GraphQL and also create pages _dynamically_ to be able to view the transformed asciidoctor html as a page on your website.

NOTE: Dynamically is a word used with causion right here. The Pages are created while building the web page and are published as static pages.

That comes in pretty handy, because I can define for example the publish date and also a category in my blog post itself via page attributes. With GraphQL I can show this data in my Blog Post as well in the overview of my recent posts or archive view.

The Query for that looks like that:

[source, graphql]
----
query PostsQuery {
      allAsciidoc(sort: { fields: pageAttributes___publishdate, order: DESC }) { # <1>
        edges {
          node {
            id
            fields {
              slug # <2>
            }
            pageAttributes { # <3>
              category
              publishdate
              title
            }
          }
        }
      }
    }
----
<1> I'm using a query that returns allAsciidoc nodes sorted by the publishdate with a descending order
<2> The slug field is a created node field which contains the file path of the asciidoctor file so we can provide a link to the page
<3> The pageAttributes node contains the page-attributes that we defined in the asciidoctor files.

== GraphQL

=== Working with gatsby-asciidoctor-transformer

Basic Usage is pretty simple. Conversion works well and fast for now.

My goal was to include Server Side Syntax Highlighting by using HighlightJS. For that I wanted to use react-highlight.js
and use the `<Highlight></Highlight>` component.
To achieve that, you have to intercept the asciidoc transformer. The Asciidoctor-transformer-plugin offers the possibility to implement
a Custom Converter Factory. But the Usage for that Custom Converter is not very well documented and I also had difficulties to getting it to work.

Therefore I can not recommend going that way right now and would recommend to choose another way. Way simpler (but also client-side) for me was to use
PrismJS. It still works fast, and for my blogging needs the solution is probably very much likely sufficent, since my blog posts will always have just a few small code-snippets.

== Conclusion

It was a straight forward experience to use GatsbyJS. If you don't have experience with ReactJS and GraphQL, you have a small learning curve at the beginning and need some time to get used to the concepts. But both are very well documented. The Documentation of Gatsby with all Tutroials is exceptionally good as well. 
This can not be stated for all of the plugins. Though, some of my hassles are infused by Asciidoctor itself, which i can't account gatsby or the plugins for.

If you want to have a more detailed insight of the described functions, you can find the repository of this blog on my GitHub Page.

== Upcoming

The next blog entry will be about Syntax Highlighting with PrismJS and Babel within GatsbyJS.